let canvas = document.getElementById("gameCanvas");
let context = canvas.getContext("2d");
// context.fillStyle = "red";
// context.fillRect(100, 50, 150, 75);
// context.fillStyle = "blue";
// context.fillRect(150, 100, 100, 50);
// context.clearRect(0, 0, 400, 200);
// context.strokeStyle = "green";
// context.lineWidth = "10";
// context.rect(150, 100, 100, 50);
// context.stroke();
// context.fillStyle = "orange";
// context.fill();
context.beginPath();
context.strokeStyle = "red";
context.lineWidth = "5";
context.moveTo(100, 50);
context.lineTo(150, 150);
context.stroke();
context.beginPath();
context.strokeStyle = "blue";
context.lineWidth = "20";
context.moveTo(200, 50);
context.lineTo(300, 50);
context.lineTo(300, 100);
context.lineCap = "round";
context.lineCap = "square";
context.lineCap = "butt";
context.stroke();
context.clearRect(0, 0, 400, 200);
context.beginPath();
context.moveTo(50, 150);
context.lineTo(150, 50);
context.lineTo(200, 150);
context.lineTo(50, 150);
context.lineWidth = "5";
context.lineCap = "butt";
context.fillStyle = "yellow";
context.closePath();
context.stroke();
context.fill();
